# 室内无人机避障训练环境配置文件

# 场景基本尺寸
scene_extent:
  x: 40.0    # 房间长度 (米)
  y: 10.0    # 房间宽度 (米)
  z: 8.0    # 房间高度 (米)

# 光照配置
lighting:
  ceil:
    color: [1.0,1.0,1.0]
    grid_x: 15
    grid_y: 6
    margin_x: 5.0
    margin_y: 2.0
    height: 7.8
    directional: 0
    cutoff_deg: 45
    attenuation: 0.1
    intensity: 0.05
  wall:
    color: [1.0,1.0,1.0]
    grid_x: 
    margin_x: 0.5
    margin_y: 0.5
    height: 6.0
    directional: 0
    cutoff_deg: 90
    attenuation: 0.001
    intensity: 0.08
  ambient:
    color: [1.0,1.0,1.0]
    num: 4
    height: 7.8
    directional: 0
    cutoff_deg: 90
    attenuation: 0.1
    intensity: 0.125

# 无人机基本参数
robot:
  size: [0.3, 0.3, 0.3]    # 无人机特征尺寸 (米)，用于自适应生成障碍物
  vts: 1.0 # 无人机时间采样倒数 （gt_speed = speed * vts）
  dp_fwd: [0.75, 5.75]  # 无人机前向运动的速度范围

# 门配置 - 无人机需要穿越的通道
gates:
  square_gate_1:
    pos: [-10,-2,1.5]
    size: [1.3,1.3,0.05]
    direction: 'x'
  square_gate_2:
    pos: [-8,0,1.7]
    size: [1.3,1.3,0.05]
    direction: 'x'
  circle_gate_1:
    pos: [-10,3,1.7]
    size: [1.4,1.4,0.1]
    direction: 'x'
  circle_gate_2:
    pos: [4,5,1.5]
    size: [1.4,1.4,0.1]
    direction: 'x'
    
# 障碍物配置
obstacles:
  roof: # meta dict for changing floating box/sphere to roof obstacles
    prob: 0.4       # less than 0.5
    height: 2.5     # roof height
    size: [1.5,1.5,1.5]  # roof obstacles expanded size.
  pillar: # vertical cylinder/box thin-pipe across z-axis
    num: 30
    pos: [[-15, -4, 0], [15, 4, 0]]
    size: [[0.05, 0.05, 4], [0.4, 0.4, 8]]
    incident: 30
  box: # floating/on roof sphere, if on_roof, can lock on second half pillar top
    num: 30
    pos: [[-15, -4, -0.1], [15, 4, 6]]
    size: [[0.2, 0.2, 0.2], [0.3, 0.3, 0.3]]
  sphere: # floating/on roof sphere, if on_roof, can lock on first half pillar top
    num: 30
    pos: [[-15, -4, -0.1], [15, 4, 6]]
    size: [[0.4, 0.4, 0.4], [0.6, 0.6, 0.6]]
  bump:  # on-ground sphere/box mimic random bump, max height of bump should less than 1m
    num: 10
    pos: [[-12, -4, 0], [12, 4, 0]]
    size: [[0.1, 0.1, 0.1], [2.9,2.9,2]]
  arrest:  # horizontal cylinder/box thin-pipe across y-axis
    num: 3
    pos: [[-12, 0, 0], [12, 0, 5]]
    size: [[0.05, 0.05, 0.05], [0.15, 0.15, 0.15]]
    incident: 10
  

# 相机配置
camera:
  debug:
    pos: [-20.0,0.0,5.0]
    lookat: [0.0,0.0,3.0]
    res: [1280, 960]
    fov: 80
    gui: false
  drone_sim:
    pos: [0.0,-4.9,5.0]
    lookat: [0.0,0.0,3.0]
    res: [1920, 1080]
    fov: 150
    gui: false
